### ISSUE TITLE
.asp -> .aspx

### ISSUE THREAD

**Issue by surfchris** [kimmknight/raweb#1]
I adopted the code to ASP.NET (.aspx) --  I'm using a Mono / XSP / Apache web server and classic ASP is not supported there. If you want to use the code you're welcome to do so. Just replace Default.asp, webfeed.asp, and Web.config with the new Default.aspx, webfeed.aspx, and Web.config. Should work exactly the same way. Code can be found on the fork https://github.com/surfchris/raweb

**Comment by bmg002** [comment]
You should make a pull request for this!  That is a nice feature to add to this so it will work as aspx which, if I am not mistaken, still works in IIS too.

**Comment by imbmf** [comment]
@surfchris it even works on raspberry pi 2.

**Comment by kimmknight** [comment]
@surfchris This is great!

I also have a PHP version that someone sent me a few years ago.

Do you guys think it would be better to include the different versions in one repo?

Otherwise, I could modify the Readme.md here and link to the ASPX/PHP versions?

Other ideas?

**Comment by MrBrianGale** [comment]
I can see multiple ways to break it up for aspx and php.  My preference would be to have a separate folder for each type in a single project.  The reason for this is it would remind me (if I was working on the code) that any changes I make in the ASP version, I should add to the ASPX and PHP version to ensure they are all feature compatible.
My thoughts on having different versions in different repos is it will be very easy for one of the 3 versions to become stale.
Plus, when a pull request is made if they are all in a single project, it is easy to reject it if only 1 or 2 of the versions are updated and not all 3.  Well, presuming the bug exists in all 3.  If it is a bug in a specific version of PHP for example, the asp and aspx one wouldn't need updating.

Thoughts?

**Comment by kimmknight** [comment]
Good thinking, MrBrianGale. I checked the PHP version and it's out of date - might update it at a later date, but won't include in the meantime.

Included the ASPX files. Thanks, surfchris!
