### ISSUE TITLE
Local host address doesn't work

### ISSUE THREAD

**Issue by kylejericson** [kimmknight/raweb#12]
I installed the feature via control panel and extracted the files to the www root folder but the local host url gives me an error.

This localhost page can’t be found No webpage was found for the web address: http://localhost/
HTTP ERROR 404

**Comment by MrBrianGale** [comment]
Did you start the appropriate services and is it listening on port 80? Did you set up ssl certs for it? If so it'll listen on port 443 (if I remember right). Is the windows firewall blocking anything?
99.9999% sure this is a configuration issue...
Alternately, you may have extracted it wrong. Still confident this is a configuration issue not a problem with the tool...

**Comment by kylejericson** [comment]
I agree just your docs don't give many steps to fix this.
I got all this installed now I just see the default IIS webpage.

**Comment by MrBrianGale** [comment]
Since you are getting the default iis page, it sounds like you didn't do step 2 correctly:
Copy the contents of the "asp\wwwroot" folder to your inetpub\wwwroot folder.

That will overwrite the default iis page.

**Comment by r0o0ot** [comment]
dosen't work also i verified the steps and still dosen't work i have installed winserver2016 and win 10 and both have iis and asp features on and i have paste the asp files in wwwroot but still didn't work

**Comment by kimmknight** [comment]
It sounds like ASP or ASPX features aren't installed. As this is working for everyone else (and in my own testing), I'm going to close this.
