### ISSUE TITLE
Adding Folder Structure / Titlebar

### ISSUE THREAD

**Issue by vanitysan** [kimmknight/raweb#14]
Good Evening,

Is it possible to add support for folders within the rdp folder. Basicly i would like to have it look and work kinda like citrix store front.
Where apps can be grouped or seperated in folders.. e.g (MS Office wich contains Excel, Word, Powerpoint,...; Creative Cloud -> wich conatins Photoshop etc....

Kind Regards
Philipp

**Comment by kimmknight** [comment]
This would indeed be a cool feature.

@vanitysan out of interest, are you using the ASP or the ASPX version?

**Comment by vanitysan** [comment]
Thanks for the response 😀

Currently im using the .asp version on IIS10
 
I will also give the .aspx a try in the future

**Comment by vanitysan** [comment]
Well im stuck now, Folder and Application Display works now correctly, The Download in the Maindirectory also works, but as soon as i want to download something within an subfolder it somehow dont give me the correct file ( meaning the original .rdp has 5kb of size but i only receive a 1kb file) and i kinda cant resolve this problem.... ive got something wrong with the server mappath i think.... or something is wrong with http url request.

**Comment by kimmknight** [comment]
Subfolders now working in the latest push to the _next_ branch. Need more testing. Some notes:

- I believe subfolders are a feature of schema 2.1. Does this need to be changed from 1.1? If so, will it break older clients?
- Subfolders will not be shown when adding webfeed via _RemoteApp and Desktop Connections_. All apps from subfolders will be there but in a flat structure
- The web interface (Default.aspx) has been updated to work with the new XML (with subfolders), however, it still displays all apps in a flat structure. I intend to add folder browsing capability
- Nested subfolders seem to work ok on the Android client (In this case the folder structure is: root > More > Even More):

<img src="https://github.com/user-attachments/assets/922c181f-f310-4224-86a7-09eacf8da04f" width="300" />

**Comment by kimmknight** [comment]
Added folder structure in commit 3dd8fab

If a modifiable title bar is still wanted, please open a new issue.
