### ISSUE TITLE
Modernize the UI design of the web interface

### ISSUE THREAD

**Issue by kimmknight** [kimmknight/raweb#18]

**Comment by akarl10** [comment]
altough not really a modernization I am currenlty experimentig here with consuming webfeed.aspx even in the website. this deduplicates a whole bunch of code

https://github.com/akarl10/raweb/tree/webfeed-api-for-frontend

**Comment by kimmknight** [comment]
This is a great idea! I've only looked at the code so far. I will try to test it out this week.

I've been tinkering with a new frontend - I will test with your loadWebFeed function 👌

**Comment by kimmknight** [comment]
> altough not really a modernization I am currenlty experimentig here with consuming webfeed.aspx even in the website. this deduplicates a whole bunch of code

I pinched your excellent idea of consuming the webfeed xml as the data source for the web interface. The code I came up with just returns a JS object of the data rather than generating HTML directly. That way I could use Vue 3 to render the HTML. Stored in feedparser.js. Also utilising Bootstrap 5 to make the design quick and easy.

I'm not entirely set on the design I've come up with, but now should be easy to update from this point.

**Comment by kimmknight** [comment]
Will probably add a darkmode switch...

**Comment by kimmknight** [comment]
<img src="https://github.com/user-attachments/assets/7259b3f7-be7c-4d3a-8795-de63a6cc63ae" width="500px">

**Comment by kimmknight** [comment]
Updated in commit 3dd8fab
