### ISSUE TITLE
Trouble after installation

### ISSUE THREAD

**Issue by Philipppoell** [kimmknight/raweb#25]
Hey,
I tryed to install the RAWeb with the setup.ps1 script. I dont get any error's but i only see this on the webside:
![image](https://github.com/user-attachments/assets/56a7376f-8c42-4ef9-817f-a89058a333dd)
The installation finished without an error i think:
![image](https://github.com/user-attachments/assets/f244583d-35ab-45ff-83cc-1e7f9ab600b4)

Did i forget something? 
Thank you!

**Comment by kimmknight** [comment]
Hi @Philipppoell thanks for reporting this.

Gosh, I didn't even think that people might be using Internet Explorer! I can fairly confidently say IE is the issue. To be sure, would you mind trying another browser?

I'll look into it. If there is an easy fix I'll implement it. If no easy fix then I want RAWeb to alert the user that their browser is incompatible.

**Comment by Philipppoell** [comment]
Hey @kimmknight,

Thank's for the fast response! Works fine with google chrome. Was a fresh server with only IE installed ;-)
Cheers and thank you for this great project!

Philipp

**Comment by kimmknight** [comment]
Going to keep this open as a reminder to check whether there is a way to implement backwards compatibility (polyfill?). If not I will update the HTML to display a message on old browsers.
