### ISSUE TITLE
Webfeed not found

### ISSUE THREAD

**Issue by s1909400** [kimmknight/raweb#3]
When putting in the webfeed URL I am told the webfeed cannot be found

**Comment by MrBrianGale** [comment]
My first steps to troubleshoot this are:
1 - log into the server you installed the raweb on
2 - navigate to the web feed URL from the installed web browser
If step 2 is successful, it means it is configured and running on the server correctly.  If not, you need to get it configured and set up on the server.
3 - find another machine on the same  network as the server and log into that
4 - navigate to the web feed URL from any installed web browser
If step 4 succeeds, then everything is configured and running correctly

My expectation is that step 4 will fail but step 2 will succeed.  In this case, it is very likely to be a firewall issue.
If step 2 fails, then you likely have done something wrong setting up the raweb tool.

Does the above help?

**Comment by s1909400** [comment]
@MrBrianGale Thank you for getting back to me, I can confirm that both step 2 and step 4 work successfully. I can see from the web inspector that the web feed is present and showing the apps, however when I attempt to add this as a workspace in the Remote Desktop app I get the following error 
![image](https://user-images.githubusercontent.com/58217704/84946905-4893d700-b0e1-11ea-8cff-79e514b07f1e.png)
This happens regardless of the "webfeed.aspx" on the end

**Comment by MrBrianGale** [comment]
Which tool is that "Add Workspace" window from?  Looking at it, I don't recognize it.
I just wanted to try to reproduce the problem and figure out if that tool's "add workspace" feature is actually expecting an raweb feed OR if it is expecting the Microsoft Windows Server RemoteApp Web feed.
My guess is that the tool you are using for adding a workspace is not expecting the format that the raweb tool is sending back OR the "Workspace" the tool is expecting is not expecting a RemoteApp Web Site.

**Comment by s1909400** [comment]
@MrBrianGale The "Add Workspace" window is from the Microsoft Remote Desktop app for Mac

**Comment by MrBrianGale** [comment]
Have you installed the server certificate on your MAC?
I do not have a MAC to test this, but quick bit of google led me to that being a possible solution.

**Comment by MrBrianGale** [comment]
Any update on this?
My best guess is the client ism missing the server certificate and thus cannot decrypt the data.

**Comment by s1909400** [comment]
Apologies for the slow reply, I’ve checked and the server certificate is installed and it is trusted. The web feed link works on windows so it appears to just be the Mac client that it has an issue with

Sent from my iPhone

On 23 Jun 2020, at 20:55, Mr. Brian Gale <notifications@github.com> wrote:

﻿

CAUTION: This email originated from outside the organisation. Only click links or open attachments when you can confirm the sender and know the content is safe. If unsure, contact ithelpdesk@glos.ac.uk


Any update on this?
My best guess is the client ism missing the server certificate and thus cannot decrypt the data.

**Comment by MrBrianGale** [comment]
Quick check on that URL you provided, the security certificate is not valid for that site.  The exact error I get is ERR_CERT_COMMON_NAME_INVALID and looking at the certificate, it does not appear to be valid for hv-100.lwild.uk.  It is valid for rds.lwild.uk.
So you will need a new certificate for hv-100.lwild.uk OR will need to use rds.lwild.uk to host the remoteapps.

A quick check on the following URL:
http://rds.lwild.uk/remoteapp/webfeed.aspx
looks like it MAY work for remoteapps as the certificate is valid and might be a remoteapp web feed.

**Comment by s1909400** [comment]
I’ve tried using the rds url but still get the same issue

Sent from my iPhone

On 23 Jun 2020, at 21:34, Mr. Brian Gale <notifications@github.com> wrote:

﻿

CAUTION: This email originated from outside the organisation. Only click links or open attachments when you can confirm the sender and know the content is safe. If unsure, contact ithelpdesk@glos.ac.uk


Quick check on that URL you provided, the security certificate is not valid for that site. The exact error I get is ERR_CERT_COMMON_NAME_INVALID and looking at the certificate, it does not appear to be valid for hv-100.lwild.uk. It is valid for rds.lwild.uk.
So you will need a new certificate for hv-100.lwild.uk OR will need to use rds.lwild.uk to host the remoteapps.

A quick check on the following URL:
http://rds.lwild.uk/remoteapp/webfeed.aspx
looks like it MAY work for remoteapps as the certificate is valid and might be a remoteapp web feed.

**Comment by MrBrianGale** [comment]
I made a typo.  that should be https://rds.lwild.uk/remoteapp/webfeed.aspx.
I don't have a MAC to test this on, but I did download the Microsoft Remote Desktop app for Windows 10 which has the option to add a workspace (kind of... they call it "Remote Resources") and it asked for a URL.  If I gave an invalid URL, I got an error of "could not find the feeds".  Changed it to the above URL and it gave no error.

All remoteapp tutorials I can find for MAC online (such as https://documentation.its.umich.edu/node/684) indicate you should be adding a remote resource, not a workspace.  I wonder if that is where things are going sideways?

If it is to be added as a workspace, my guess is something is preventing the remote desktop  app from seeing your installed certificates, the certificates are installed to the wrong location, or the remote desktop app is out of date.
I am not aware of any  free method to load up a MAC VM (cloud or local) or I'd spin something up to test it out.

**Comment by MrBrianGale** [comment]
Did updating the Remote Desktop tool for MAC or adding a remote resource instead of a workspace help?

**Comment by MrBrianGale** [comment]
Due to lack of response and the issue appearing to be related to the client being used, not the RAWeb tool, this issue is being marked as closed.

If this was closed in error, please reopen.
