### ISSUE TITLE
Russian characters in application names are not displayed correctly

### ISSUE THREAD

**Issue by sashaqwert** [kimmknight/raweb#4]
I have been using RemoteAppTool for a long time. I decided to install raWeb today, but I got krakozyabry:
![изображение](https://user-images.githubusercontent.com/24974508/84886983-ce8e2e80-b09d-11ea-9536-6c54da125858.png)
I attach the problem files:

[remoteApps.zip](https://github.com/kimmknight/raweb/files/4792103/remoteApps.zip)

**Comment by sashaqwert** [comment]
I'm sent pull request to fix it.
With normal encoding, it will look like this:
![изображение](https://user-images.githubusercontent.com/24974508/84901266-e53f8000-b0b3-11ea-9e5e-30ccc1caa067.png)

**Comment by kimmknight** [comment]
Looks good
